name: Fully compile build and upload on Test PyPi

on:
  push:
    tags:
      - v*

jobs:
  # Only the job is the important.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08
        with:
          python-version: '3.10'
