name: Fully compile build and upload on Test PyPi

on:
  push:
    tags:
      - v*

jobs:
  # Only the job is the important.
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@c4e89fac7e8767b327bbad6cb4d859eda999cf08
        with:
          python-version: '3.10'
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Install build dependencies
        run: python3 -m pip install -r requirements-build.txt

      - name: Build
        run: python3 -m build

      - name: List shasums
        run: shasum -a 256 dist/*

      - name: Store build artifacts
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: build-artifacts # dest
          path: dist # src

  upload:
    runs-on: ubuntu-latest
    needs: build
    environment: Ejaculate
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
        with:
          name: build-artifacts # src
          path: dist # dest

      - name: Upload binary wheel and source tarball
        uses: pypa/gh-action-pypi-publish@717ba43cfbb0387f6ce311b169a825772f54d295
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

